export default [
    { 
      _id: "001",
      title: 'Apex Legends',
      game_url: 'https://www.ea.com/games/apex-legends',
      genre: "Shooter",
      max_players: 3,
      platform: ['PC', "PS4" ],
      publisher: "Electronic Arts",
      developer: "Electronic Arts",
      release_date: "2019-02-04",
    },
    {
      _id: "002",
      title: 'Counter Strike: Global Offensive',
      game_url: 'https://www.ea.com/ghttps://store.steampowered.com/app/730/CounterStrike_Global_Offensive/ames/apex-legends',
      genre: "Shooter",
      max_players: 5,
      platform: ['PC'],
      publisher: "Valve",
      developer: "Valve, Hidden Path Entertainment",
      release_date: "2019-02-04",
    },
    {
      _id: "003",
      title: 'Valorant',
      game_url: 'https://playvalorant.com',
      genre: "Shooter",
      max_players: 5,
      platform: ['PC'],
      publisher: "Riot Games",
      developer: "Riot Games",
      release_date: "2020-06-02",
    },
    {
      _id: "004",
      title: 'Dota 2',
      game_url: 'https://www.dota2.com/home',
      genre: "Moba",
      max_players: 5,
      platform: ['PC'],
      publisher: "Valve",
      developer: "Valve",
      release_date: "2013-07-09",  
    },
    {
      _id: "005",
      title: 'Genshin Impact',
      game_url: 'https://genshin.mihoyo.com/en/',
      genre: "Action RPG",
      max_players: 4,
      platform: ['PC', 'PS4', 'Mobile'],
      publisher: "miHoYo",
      developer: "miHoYo",
      release_date: "2020-09-28",  
    }
]