const userList = [
  {
    id: 1,
    email: "rold@ga.com",
    password: "123456",
    firstName: "Jerrold",
    lastName: "Tan",
    handleId: "roldroldxz",
    location: "Singapore",
    bio: "roldroldrold everyday",
    rating: ["5"],
    friendList: ["WhereMyLychee", "Cheeseboi", "Yaoyaoyao"],
  },
  {
    email: "bryan@ga.com",
    password: "123456",
    firstName: "Bryan",
    lastName: "Boey",
    handleId: "WhereMyLychee",
    location: "Singapore",
    bio: "i eat codes for dinner",
    rating: ["5"],
    friendList: ["roldroldxz", "Cheeseboi", "Yaoyaoyao"],
  },
  {
    email: "Faeriq@ga.com",
    password: "123456",
    firstName: "Faeriq",
    lastName: "Ramley",
    handleId: "cheese",
    location: "Singapore",
    bio: "aspiring Vtuber",
    rating: ["5"],
    friendList: ["Bry", "roldroldxz", "Yaoyaoyao"],
  },
  {
    email: "rold@ga.com",
    password: "123456",
    firstName: "Jin",
    lastName: "Yao",
    handleId: "Yaoyaoyao",
    location: "Singapore",
    bio: "maymaymay",
    rating: ["5"],
    friendList: ["Bry", "Cheeseboi", "Yaoyaoyao"],
  },
];

module.exports = userList;
